#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Jan 01, 2024 10:12:50 PM CET  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) cornsilk3
set vTcl(actual_gui_fg) black
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) cornsilk-light



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background cornsilk3 -highlightbackground cornsilk3 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 642x641+2311+178
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    canvas "$top.can57" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can57" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can58" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can58" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can60" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can60" "Canvas5" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can61" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can61" "Canvas6" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can59" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can59" "Canvas4" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can56" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can56" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can62" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can62" "Canvas7" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can63" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can63" "Canvas8" vTcl:WidgetProc "Toplevel1" 1
    canvas "$top.can64" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$top.can64" "Canvas9" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can57 \
        -in $top -x 221 -y 11 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can58 \
        -in $top -x 431 -y 11 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can60 \
        -in $top -x 221 -y 221 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can61 \
        -in $top -x 431 -y 221 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can59 \
        -in $top -x 11 -y 221 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can56 \
        -in $top -x 11 -y 11 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can62 \
        -in $top -x 12 -y 431 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can63 \
        -in $top -x 221 -y 431 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $top.can64 \
        -in $top -x 431 -y 431 -width 200 -height 200 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

