#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jan 01, 2024 10:12:56 PM CET  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import game_board_support

_bgcolor = 'cornsilk3'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("642x641+2311+178")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="cornsilk3")
        top.configure(highlightbackground="cornsilk3")
        top.configure(highlightcolor="black")

        self.top = top

        self.Canvas2 = tk.Canvas(self.top)
        self.Canvas2.place(x=221, y=11, height=200, width=200)
        self.Canvas2.configure(background="wheat")
        self.Canvas2.configure(borderwidth="2")
        self.Canvas2.configure(highlightbackground="wheat")
        self.Canvas2.configure(relief="ridge")
        self.Canvas2.configure(selectbackground="#d9d9d9")

        self.Canvas3 = tk.Canvas(self.top)
        self.Canvas3.place(x=431, y=11, height=200, width=200)
        self.Canvas3.configure(background="wheat")
        self.Canvas3.configure(borderwidth="2")
        self.Canvas3.configure(highlightbackground="wheat")
        self.Canvas3.configure(relief="ridge")
        self.Canvas3.configure(selectbackground="#d9d9d9")

        self.Canvas5 = tk.Canvas(self.top)
        self.Canvas5.place(x=221, y=221, height=200, width=200)
        self.Canvas5.configure(background="wheat")
        self.Canvas5.configure(borderwidth="2")
        self.Canvas5.configure(highlightbackground="wheat")
        self.Canvas5.configure(relief="ridge")
        self.Canvas5.configure(selectbackground="#d9d9d9")

        self.Canvas6 = tk.Canvas(self.top)
        self.Canvas6.place(x=431, y=221, height=200, width=200)
        self.Canvas6.configure(background="wheat")
        self.Canvas6.configure(borderwidth="2")
        self.Canvas6.configure(highlightbackground="wheat")
        self.Canvas6.configure(relief="ridge")
        self.Canvas6.configure(selectbackground="#d9d9d9")

        self.Canvas4 = tk.Canvas(self.top)
        self.Canvas4.place(x=11, y=221, height=200, width=200)
        self.Canvas4.configure(background="wheat")
        self.Canvas4.configure(borderwidth="2")
        self.Canvas4.configure(highlightbackground="wheat")
        self.Canvas4.configure(relief="ridge")
        self.Canvas4.configure(selectbackground="#d9d9d9")

        self.Canvas1 = tk.Canvas(self.top)
        self.Canvas1.place(x=11, y=11, height=200, width=200)
        self.Canvas1.configure(background="wheat")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="wheat")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")

        self.Canvas7 = tk.Canvas(self.top)
        self.Canvas7.place(x=12, y=431, height=200, width=200)
        self.Canvas7.configure(background="wheat")
        self.Canvas7.configure(borderwidth="2")
        self.Canvas7.configure(highlightbackground="wheat")
        self.Canvas7.configure(relief="ridge")
        self.Canvas7.configure(selectbackground="#d9d9d9")

        self.Canvas8 = tk.Canvas(self.top)
        self.Canvas8.place(x=221, y=431, height=200, width=200)
        self.Canvas8.configure(background="wheat")
        self.Canvas8.configure(borderwidth="2")
        self.Canvas8.configure(highlightbackground="wheat")
        self.Canvas8.configure(relief="ridge")
        self.Canvas8.configure(selectbackground="#d9d9d9")

        self.Canvas9 = tk.Canvas(self.top)
        self.Canvas9.place(x=431, y=431, height=200, width=200)
        self.Canvas9.configure(background="wheat")
        self.Canvas9.configure(borderwidth="2")
        self.Canvas9.configure(highlightbackground="wheat")
        self.Canvas9.configure(relief="ridge")
        self.Canvas9.configure(selectbackground="#d9d9d9")

def start_up():
    game_board_support.main()

if __name__ == '__main__':
    game_board_support.main()
