#############################################################################
# Generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#  Jan 03, 2024 01:45:24 PM CET  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) cornsilk3
set vTcl(actual_gui_fg) black
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 0
set vTcl(mode) Absolute
set vTcl(project_theme) cornsilk-dark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu $top.m47 -background cornsilk4 -highlightbackground cornsilk4 \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 666x706+485+168
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3825 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m47" \
        -activebackground #d9d9d9 -activeforeground black \
        -font "-family {DejaVu Sans} -size 10" -tearoff 0 
    ttk::button "$top.tBu49" \
        -command "on_TBtnPlayer1" -text "Player1" -compound left 
    vTcl:DefineAlias "$top.tBu49" "TBtnPlayer1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tBu49
    ttk::button "$top.tBu50" \
        -command "on_TBtnPlayer2" -text "Player2" -compound left 
    vTcl:DefineAlias "$top.tBu50" "TBtnPlayer2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tBu50
    ttk::button "$top.tBu51" \
        -command "on_TBtnPlayer3" -text "Player3" -compound left 
    vTcl:DefineAlias "$top.tBu51" "TBtnPlayer3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tBu51
    ttk::button "$top.tBu52" \
        -command "on_TBtnPlayer4" -text "Player4" -compound left 
    vTcl:DefineAlias "$top.tBu52" "TBtnPlayer4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $top.tBu52
    ttk::frame "$top.tFr53" \
        -borderwidth 2 -relief groove -width 642 -height 641 
    vTcl:DefineAlias "$top.tFr53" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr53
    canvas "$site_3_0.can54" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can54" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can54
    canvas "$site_3_0.can55" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 190 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 200 
    vTcl:DefineAlias "$site_3_0.can55" "Canvas2" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can55
    canvas "$site_3_0.can65" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can65" "Canvas3" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can65
    canvas "$site_3_0.can66" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can66" "Canvas4" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can66
    canvas "$site_3_0.can47" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can47" "Canvas5" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can47
    canvas "$site_3_0.can48" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can48" "Canvas6" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can48
    canvas "$site_3_0.can53" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can53" "Canvas7" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can53
    canvas "$site_3_0.can67" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can67" "Canvas8" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can67
    canvas "$site_3_0.can68" \
        -background wheat -borderwidth 2 -closeenough 1.0 -height 75 \
        -highlightbackground wheat -highlightcolor black \
        -insertbackground black -relief ridge -selectbackground #d9d9d9 \
        -selectforeground black -width 125 
    vTcl:DefineAlias "$site_3_0.can68" "Canvas9" vTcl:WidgetProc "Toplevel1" 1
    vTcl:copy_lock $site_3_0.can68
    place $site_3_0.can54 \
        -in $site_3_0 -x 10 -y 10 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can55 \
        -in $site_3_0 -x 221 -y 11 -width 200 -relwidth 0 -height 200 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can65 \
        -in $site_3_0 -x 431 -y 11 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can66 \
        -in $site_3_0 -x 11 -y 221 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can47 \
        -in $site_3_0 -x 221 -y 221 -width 200 -relwidth 0 -height 200 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can48 \
        -in $site_3_0 -x 431 -y 221 -width 200 -relwidth 0 -height 200 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.can53 \
        -in $site_3_0 -x 11 -y 431 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can67 \
        -in $site_3_0 -x 221 -y 431 -width 200 -height 200 -anchor nw \
        -bordermode ignore 
    place $site_3_0.can68 \
        -in $site_3_0 -x 431 -y 431 -width 200 -relwidth 0 -height 200 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.tFr53
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tBu49 \
        -in $top -x 70 -y 660 -width 75 -relwidth 0 -height 35 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu50 \
        -in $top -x 221 -y 660 -width 75 -height 35 -anchor nw \
        -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 369 -y 660 -width 75 -height 35 -anchor nw \
        -bordermode ignore 
    place $top.tBu52 \
        -in $top -x 517 -y 660 -width 75 -height 35 -anchor nw \
        -bordermode ignore 
    place $top.tFr53 \
        -in $top -x 10 -y 10 -width 642 -relwidth 0 -height 641 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

