#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jan 03, 2024 01:46:23 PM CET  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import fourplayer

# Importing other required modules
try:
    from PIL import Image, ImageTk
    import random
except:
    # can't import essential modules
    sys.exit()

#   ========================================================
#     Create share module and import it into the script
#   ========================================================
import os
module_name = "shared"   # empty_module
# Create the empty module file
with open(f"{module_name}.py", "w") as file:
    pass  # This creates an empty file
# Check if the file exists before importing
if os.path.isfile(f"{module_name}.py"):
    import importlib.util
    spec = importlib.util.spec_from_file_location(module_name, f"{module_name}.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
else:
    print(f"File '{module_name}.py' does not exist. Failed to import the module.")
sh=importlib   # sh is alias shared for short
#   ========================================================

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = fourplayer.Toplevel1(_top1)
    fourplayer_startup()
    root.mainloop()

def fourplayer_startup():
    _top1.title("fourplayer")
    sh.im_dict = {}   # a dict to hold all images from disc
    sh.rnd_im_dict={}   # a dict to hold all images in random orderinit_players_image_dict(sh.rnd_im_dict)
    # init a image dict for each player
    sh.player1_im={}
    sh.player2_im={}
    sh.player3_im={}
    sh.player4_im={}
    sh.player_lst=[sh.player1_im, sh.player2_im, sh.player3_im, sh.player4_im]
    sh.player=0
    sh.form_color_lst=['blue', 'green', 'yellow', 'red']
    sh.style = ttk.Style()
    make_mystyle()
    sh.id_lst=['MyTButton1.TButton','MyTButton2.TButton','MyTButton3.TButton','MyTButton4.TButton']
    sh.button_lst=[_w1.TBtnPlayer1, _w1.TBtnPlayer2, _w1.TBtnPlayer3, _w1.TBtnPlayer4]    
    set_form_color(sh.player)
    set_button_color()
    init_canvas()
    init_path()
    img_number = 36   # set number of images to load
    # make a list of all image names by List Comprehension
    sh.im_lst=[f'{x}.png' for x in range(1,img_number+1)]
    ## print(im_lst)   # ['1.png', '2.png', '3.png', '4.png', '5.png', '6.png', '7.png', '8.png', '9.png', '10.png', '11.png', '12.png', '13.png', '14.png', '15.png', '16.png', '17.png', '18.png', '19.png', '20.png', '21.png', '22.png', '23.png', '24.png', '25.png', '26.png', '27.png', '28.png', '29.png', '30.png', '31.png', '32.png', '33.png', '34.png', '35.png', '36.png']
    init_image_dict()
    sh.rnd_im_dict = dict_randomization(sh.im_dict)
    init_players_image_dict(sh.rnd_im_dict)
    player_dict=sh.player_lst[sh.player]
    display_image(player_dict) # player 1 at init

#   ========================================================
#     Init Section
#   ========================================================

def init_canvas():
    sh.can1 = _w1.Canvas1
    sh.can2 = _w1.Canvas2
    sh.can3 = _w1.Canvas3
    sh.can4 = _w1.Canvas4
    sh.can5 = _w1.Canvas5
    sh.can6 = _w1.Canvas6
    sh.can7 = _w1.Canvas7
    sh.can8 = _w1.Canvas8
    sh.can9 = _w1.Canvas9
    sh.canvas_lst = [sh.can1, sh.can2, sh.can3, sh.can4, sh.can5, sh.can6, sh.can7, sh.can8, sh.can9]

def init_path():
    # parent dir path
    sh.path_parent = os.getcwd()
    # photo dir path
    sh.path_photo = sh.path_parent+"/assets/lotto_graphics"

def init_image_dict():
    # make a dicts with all images
    sh._img=[]
    global _img
    for inx, im in enumerate(sh.im_lst):
        if inx < 36:
            # join path and filename to photo_location for a photo
            fn = im
            photo_location = os.path.join(sh.path_photo,fn)
            #loading the image 
            original = Image.open(photo_location)
            # Create a thumbnail
            thumbnail_size=(200,200)
            original.thumbnail(thumbnail_size)   # 600x600 -> 200x200
            sh._img.append(inx+1)
            sh._img[inx] = ImageTk.PhotoImage(original)
            # save original to dict
            _img=f'{sh._img[inx]}'
            if not _img in sh.im_dict:
                sh.im_dict[_img] = ImageTk.PhotoImage(original)

def init_players_image_dict(rnd_im_dict):
    # split dict into four equal chunks
    cnt=1
    for key, values in rnd_im_dict.items():
        if cnt==1:
            sh.player1_im[key]=values
        elif cnt==2:
            sh.player2_im[key]=values
        elif cnt==3:
            sh.player3_im[key]=values
        elif cnt==4:
            sh.player4_im[key]=values
        cnt+=1
        if cnt==5:
            cnt=1

#   ========================================================
#     Support Section
#   ========================================================

def dict_randomization(d):
    ''' How To Iterate Over A Python Dictionary In Random Order? 
        To iterate over the dictionary items in random order get 
        the list of items in a tuple with .items() 
        then shuffle and iterate through this list using 
        the shuffle() and make a new dict with the result'''
    rnd_d={}
    items = list(d.items()) # List of tuples of (key,values)
    random.shuffle(items)
    for key, value in items:
        # print(key, ":", value)
        rnd_d[key]=value
    return rnd_d

def make_mystyle():
    # set TFrame style
    sh.style.map('TFrame',
                background=[('active', '#8B8878'),   # bg2),
                            ('disabled', 'gray76'),
                            ('readonly', 'firebrick2')],
                bordercolor=[('active', '#FFFAFA'),   # fg2),
                            ('disabled', 'gray24'),   # fg1),
                            ('readonly', 'gray50')]   # fg3)],
                )
    sh.style.map('TButton',
                background=[('active', '#8B8878'),
                            ('disabled', 'gray76'),
                            ('readonly', 'firebrick2')],
                foreground=[('active', '#FFFAFA'),
                            ('disabled', 'gray24'),
                            ('readonly', 'gray50')]
                )    

def set_form_color(player):
    # change background color to player color
    sh.style.configure('MyTFrame.TFrame',
                    background=sh.form_color_lst[player],
                    bordercolor='gray24')
    _w1.TFrame1.configure(style='MyTFrame.TFrame')

def set_button_color():
    for inx, button in enumerate(sh.button_lst):
        sh.style.configure(sh.id_lst[inx],
                    background='#8B8878',
                    foreground=sh.form_color_lst[inx]
                        )
        button.configure(style=sh.id_lst[inx])

def display_image(player_dict):
    num=0
    for key, value in player_dict.items():
        set_form_color(sh.player)
        sh.canvas_lst[num].create_image((100, 100), image=value, anchor='center')   # remember x,y is center of image
        num+=1

#   ========================================================
#     Program Startup
#   ========================================================

def on_TBtnPlayer1(*args):
    if _debug:
        print('fourplayer_support.on_TBtnPlayer1')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    sh.player=0
    player_dict=sh.player_lst[sh.player]
    display_image(player_dict)

def on_TBtnPlayer2(*args):
    if _debug:
        print('fourplayer_support.on_TBtnPlayer2')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    sh.player=1
    player_dict=sh.player_lst[sh.player]
    display_image(player_dict)

def on_TBtnPlayer3(*args):
    if _debug:
        print('fourplayer_support.on_TBtnPlayer3')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    sh.player=2
    player_dict=sh.player_lst[sh.player]
    display_image(player_dict)

def on_TBtnPlayer4(*args):
    if _debug:
        print('fourplayer_support.on_TBtnPlayer4')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    sh.player=3
    player_dict=sh.player_lst[sh.player]
    display_image(player_dict)

if __name__ == '__main__':
    fourplayer.start_up()
