#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.0
#  in conjunction with Tcl version 8.6
#    Jan 03, 2024 01:45:25 PM CET  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_location = os.path.dirname(__file__)

import fourplayer_support

_bgcolor = 'cornsilk4'
_fgcolor = 'black'
_tabfg1 = 'black' 
_tabfg2 = 'white' 
_bgmode = 'light' 
_tabbg1 = '#d9d9d9' 
_tabbg2 = 'gray40' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran: return        
    try: fourplayer_support.root.tk.call('source',
                os.path.join(_location, 'themes', 'cornsilk-dark.tcl'))
    except: pass
    style = ttk.Style()
    style.theme_use('cornsilk-dark')
    style.configure('.', font = "TkDefaultFont")
    _style_code_ran = 1

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("666x706+485+168")
        top.minsize(1, 1)
        top.maxsize(3825, 1050)
        top.resizable(0,  0)
        top.title("Toplevel 0")
        top.configure(background="cornsilk4")
        top.configure(highlightbackground="cornsilk4")
        top.configure(highlightcolor="black")

        self.top = top

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='cornsilk4'
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        _style_code()
        self.TBtnPlayer1 = ttk.Button(self.top)
        self.TBtnPlayer1.place(x=70, y=660, height=35, width=75)
        self.TBtnPlayer1.configure(command=fourplayer_support.on_TBtnPlayer1)
        self.TBtnPlayer1.configure(text='''Player1''')
        self.TBtnPlayer1.configure(compound='left')

        self.TBtnPlayer2 = ttk.Button(self.top)
        self.TBtnPlayer2.place(x=221, y=660, height=35, width=75)
        self.TBtnPlayer2.configure(command=fourplayer_support.on_TBtnPlayer2)
        self.TBtnPlayer2.configure(text='''Player2''')
        self.TBtnPlayer2.configure(compound='left')

        self.TBtnPlayer3 = ttk.Button(self.top)
        self.TBtnPlayer3.place(x=369, y=660, height=35, width=75)
        self.TBtnPlayer3.configure(command=fourplayer_support.on_TBtnPlayer3)
        self.TBtnPlayer3.configure(text='''Player3''')
        self.TBtnPlayer3.configure(compound='left')

        self.TBtnPlayer4 = ttk.Button(self.top)
        self.TBtnPlayer4.place(x=517, y=660, height=35, width=75)
        self.TBtnPlayer4.configure(command=fourplayer_support.on_TBtnPlayer4)
        self.TBtnPlayer4.configure(text='''Player4''')
        self.TBtnPlayer4.configure(compound='left')

        self.TFrame1 = ttk.Frame(self.top)
        self.TFrame1.place(x=10, y=10, height=641, width=642)
        self.TFrame1.configure(relief='groove')
        self.TFrame1.configure(borderwidth="2")
        self.TFrame1.configure(relief="groove")

        self.Canvas1 = tk.Canvas(self.TFrame1)
        self.Canvas1.place(x=10, y=10, height=200, width=200)
        self.Canvas1.configure(background="wheat")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="wheat")
        self.Canvas1.configure(relief="ridge")
        self.Canvas1.configure(selectbackground="#d9d9d9")

        self.Canvas2 = tk.Canvas(self.TFrame1)
        self.Canvas2.place(x=221, y=11, height=200, width=200)
        self.Canvas2.configure(background="wheat")
        self.Canvas2.configure(borderwidth="2")
        self.Canvas2.configure(highlightbackground="wheat")
        self.Canvas2.configure(relief="ridge")
        self.Canvas2.configure(selectbackground="#d9d9d9")

        self.Canvas3 = tk.Canvas(self.TFrame1)
        self.Canvas3.place(x=431, y=11, height=200, width=200)
        self.Canvas3.configure(background="wheat")
        self.Canvas3.configure(borderwidth="2")
        self.Canvas3.configure(highlightbackground="wheat")
        self.Canvas3.configure(relief="ridge")
        self.Canvas3.configure(selectbackground="#d9d9d9")

        self.Canvas4 = tk.Canvas(self.TFrame1)
        self.Canvas4.place(x=11, y=221, height=200, width=200)
        self.Canvas4.configure(background="wheat")
        self.Canvas4.configure(borderwidth="2")
        self.Canvas4.configure(highlightbackground="wheat")
        self.Canvas4.configure(relief="ridge")
        self.Canvas4.configure(selectbackground="#d9d9d9")

        self.Canvas5 = tk.Canvas(self.TFrame1)
        self.Canvas5.place(x=221, y=221, height=200, width=200)
        self.Canvas5.configure(background="wheat")
        self.Canvas5.configure(borderwidth="2")
        self.Canvas5.configure(highlightbackground="wheat")
        self.Canvas5.configure(relief="ridge")
        self.Canvas5.configure(selectbackground="#d9d9d9")

        self.Canvas6 = tk.Canvas(self.TFrame1)
        self.Canvas6.place(x=431, y=221, height=200, width=200)
        self.Canvas6.configure(background="wheat")
        self.Canvas6.configure(borderwidth="2")
        self.Canvas6.configure(highlightbackground="wheat")
        self.Canvas6.configure(relief="ridge")
        self.Canvas6.configure(selectbackground="#d9d9d9")

        self.Canvas7 = tk.Canvas(self.TFrame1)
        self.Canvas7.place(x=11, y=431, height=200, width=200)
        self.Canvas7.configure(background="wheat")
        self.Canvas7.configure(borderwidth="2")
        self.Canvas7.configure(highlightbackground="wheat")
        self.Canvas7.configure(relief="ridge")
        self.Canvas7.configure(selectbackground="#d9d9d9")

        self.Canvas8 = tk.Canvas(self.TFrame1)
        self.Canvas8.place(x=221, y=431, height=200, width=200)
        self.Canvas8.configure(background="wheat")
        self.Canvas8.configure(borderwidth="2")
        self.Canvas8.configure(highlightbackground="wheat")
        self.Canvas8.configure(relief="ridge")
        self.Canvas8.configure(selectbackground="#d9d9d9")

        self.Canvas9 = tk.Canvas(self.TFrame1)
        self.Canvas9.place(x=431, y=431, height=200, width=200)
        self.Canvas9.configure(background="wheat")
        self.Canvas9.configure(borderwidth="2")
        self.Canvas9.configure(highlightbackground="wheat")
        self.Canvas9.configure(relief="ridge")
        self.Canvas9.configure(selectbackground="#d9d9d9")

def start_up():
    fourplayer_support.main()

if __name__ == '__main__':
    fourplayer_support.main()




