#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.0s
#  in conjunction with Tcl version 8.6
#    Jul 08, 2023 05:32:34 AM PDT  platform: Linux

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import theme

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = theme.Toplevel1(_top1)
    root.mainloop()

def quit(*args):
    if _debug:
        print('theme_support.quit')
        for arg in args:
            print ('    another arg:', arg)
        sys.stdout.flush()
    sys.exit()

if __name__ == '__main__':
    theme.start_up()




